package com.qhit.lh.gr3.cyh.exam.classinfo.bean;
// Generated 2018-1-9 17:47:24 by Hibernate Tools 3.4.0.CR1

import static org.hamcrest.CoreMatchers.endsWith;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.qhit.lh.gr3.cyh.exam.common.bean.TStudent;
import com.qhit.lh.gr3.cyh.exam.paper.bean.PaperClass;

/**
 * TClassInfo generated by hbm2java
 */
public class TClassInfo implements java.io.Serializable {

	private String ccode;
	private String cname;
	private String major;
	private int insId;
	private int iecId;
	private Date cdate;
	private Integer g1num;
	private Integer g2num;
	private Integer g3num;
	private Integer ccodeId;
	private String cremark;
	// 1-n
	private Set<PaperClass> pacls=new HashSet<PaperClass>();
	//1-n
	private Set<TStudent> stus=new HashSet<TStudent>();
	
	public TClassInfo() {
	}

	public TClassInfo(String ccode, String cname, String major, int insId, int iecId, Date cdate) {
		this.ccode = ccode;
		this.cname = cname;
		this.major = major;
		this.insId = insId;
		this.iecId = iecId;
		this.cdate = cdate;
	}

	public TClassInfo(String ccode, String cname, String major, int insId, int iecId, Date cdate, Integer g1num,
			Integer g2num, Integer g3num, Integer ccodeId, String cremark) {
		this.ccode = ccode;
		this.cname = cname;
		this.major = major;
		this.insId = insId;
		this.iecId = iecId;
		this.cdate = cdate;
		this.g1num = g1num;
		this.g2num = g2num;
		this.g3num = g3num;
		this.ccodeId = ccodeId;
		this.cremark = cremark;
	}

	public String getCcode() {
		return this.ccode;
	}

	public void setCcode(String ccode) {
		this.ccode = ccode;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public int getInsId() {
		return this.insId;
	}

	public void setInsId(int insId) {
		this.insId = insId;
	}

	public int getIecId() {
		return this.iecId;
	}

	public void setIecId(int iecId) {
		this.iecId = iecId;
	}

	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public Integer getG1num() {
		return this.g1num;
	}

	public void setG1num(Integer g1num) {
		this.g1num = g1num;
	}

	public Integer getG2num() {
		return this.g2num;
	}

	public void setG2num(Integer g2num) {
		this.g2num = g2num;
	}

	public Integer getG3num() {
		return this.g3num;
	}

	public void setG3num(Integer g3num) {
		this.g3num = g3num;
	}

	public Integer getCcodeId() {
		return this.ccodeId;
	}

	public void setCcodeId(Integer ccodeId) {
		this.ccodeId = ccodeId;
	}

	public String getCremark() {
		return this.cremark;
	}

	public void setCremark(String cremark) {
		this.cremark = cremark;
	}

	public Set<PaperClass> getPacls() {
		return pacls;
	}

	public void setPacls(Set<PaperClass> pacls) {
		this.pacls = pacls;
	}

	public Set<TStudent> getStus() {
		return stus;
	}

	public void setStus(Set<TStudent> stus) {
		this.stus = stus;
	}
}
