package com.qhit.lh.gr3.cyh.exam.common.bean;

import java.util.HashSet;
import java.util.Set;

import com.qhit.lh.gr3.cyh.exam.examScores.bean.TUserScores;

// Generated 2018-1-22 18:17:07 by Hibernate Tools 3.4.0.CR1

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private String name;
	private String pwd;
	private int role;
	//1-1
	private TStudent student;
	private TTeacher teacher;
	//1-n
	private Set<TUserScores> userScores=new HashSet<TUserScores>();
	public TUser() {
	}

	public TUser(String name, String pwd, int role) {
		this.name = name;
		this.pwd = pwd;
		this.role = role;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	public TStudent getStudent() {
		return student;
	}

	public void setStudent(TStudent student) {
		this.student = student;
	}

	public TTeacher getTeacher() {
		return teacher;
	}

	public void setTeacher(TTeacher teacher) {
		this.teacher = teacher;
	}

	public Set<TUserScores> getUserScores() {
		return userScores;
	}

	public void setUserScores(Set<TUserScores> userScores) {
		this.userScores = userScores;
	}

}
