package com.qhit.lh.gr3.cyh.exam.question.bean;

import java.util.HashSet;
import java.util.Set;

import com.qhit.lh.gr3.cyh.exam.paper.bean.TPaper;

// Generated 2018-1-22 18:32:42 by Hibernate Tools 3.4.0.CR1

/**
 * TCourse generated by hbm2java
 */
public class TCourse implements java.io.Serializable {

	private int csId;
	private String csName;
	private String stage;
	private String major;
	//1-n
	private Set<TMachineTest> machineTests=new HashSet<TMachineTest>();
	private Set<TWrittenTest> writtenTests=new HashSet<TWrittenTest>();
	private Set<TPaper> papers=new HashSet<TPaper>();
	public TCourse() {
	}

	public TCourse(int csId, String csName, String stage, String major) {
		this.csId = csId;
		this.csName = csName;
		this.stage = stage;
		this.major = major;
	}

	public int getCsId() {
		return this.csId;
	}

	public void setCsId(int csId) {
		this.csId = csId;
	}

	public String getCsName() {
		return this.csName;
	}

	public void setCsName(String csName) {
		this.csName = csName;
	}

	public String getStage() {
		return this.stage;
	}

	public void setStage(String stage) {
		this.stage = stage;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public Set<TMachineTest> getMachineTests() {
		return machineTests;
	}

	public Set<TWrittenTest> getWrittenTests() {
		return writtenTests;
	}

	public void setMachineTests(Set<TMachineTest> machineTests) {
		this.machineTests = machineTests;
	}

	public void setWrittenTests(Set<TWrittenTest> writtenTests) {
		this.writtenTests = writtenTests;
	}

	public Set<TPaper> getPapers() {
		return papers;
	}

	public void setPapers(Set<TPaper> papers) {
		this.papers = papers;
	}

	@Override
	public String toString() {
		return "TCourse [csId=" + csId + ", csName=" + csName + ", stage=" + stage + ", major=" + major + "]";
	}

}
