package com.qhit.lh.gr3.cyh.exam.question.bean;
// Generated 2018-1-22 18:32:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.qhit.lh.gr3.cyh.exam.paper.bean.TPaper;

/**
 * TMachineTest generated by hbm2java
 */
public class TMachineTest implements java.io.Serializable {

	private int qid;
	private String qtitle;
	private String degree;
	private int csId;
	private String chapter;
	// n-1
	private TCourse course;
	// n-n
	private Set<TPaper> papers = new HashSet<TPaper>();

	public TMachineTest() {
	}

	public TMachineTest(int qid, String qtitle, String degree, int csId) {
		this.qid = qid;
		this.qtitle = qtitle;
		this.degree = degree;
		this.csId = csId;
	}

	public TMachineTest(int qid, String qtitle, String degree, int csId, String chapter) {
		this.qid = qid;
		this.qtitle = qtitle;
		this.degree = degree;
		this.csId = csId;
		this.chapter = chapter;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public String getQtitle() {
		return this.qtitle;
	}

	public void setQtitle(String qtitle) {
		this.qtitle = qtitle;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public int getCsId() {
		return this.csId;
	}

	public void setCsId(int csId) {
		this.csId = csId;
	}

	public String getChapter() {
		return this.chapter;
	}

	public void setChapter(String chapter) {
		this.chapter = chapter;
	}

	public TCourse getCourse() {
		return course;
	}

	public void setCourse(TCourse course) {
		this.course = course;
	}

	public Set<TPaper> getPapers() {
		return papers;
	}

	public void setPapers(Set<TPaper> papers) {
		this.papers = papers;
	}

}
