package com.qhit.lh.gr3.cyh.exam.question.bean;

import java.util.HashSet;
import java.util.Set;

import com.qhit.lh.gr3.cyh.exam.paper.bean.TPaper;

// Generated 2018-1-22 18:32:42 by Hibernate Tools 3.4.0.CR1

/**
 * TWrittenTest generated by hbm2java
 */
public class TWrittenTest implements java.io.Serializable {

	private int qid;
	private String qtype;
	private String qtitle;
	private String optionA;
	private String optionB;
	private String optionC;
	private String optionD;
	private String answer;
	private String degree;
	private int csId;
	private String chapter;
	// n-1
	private TCourse course;
	//n-n
	public TWrittenTest() {
	}

	public TWrittenTest(int qid, String qtype, String qtitle, String optionA, String optionB, String optionC,
			String optionD, String degree, int csId) {
		this.qid = qid;
		this.qtype = qtype;
		this.qtitle = qtitle;
		this.optionA = optionA;
		this.optionB = optionB;
		this.optionC = optionC;
		this.optionD = optionD;
		this.degree = degree;
		this.csId = csId;
	}

	public TWrittenTest(int qid, String qtype, String qtitle, String optionA, String optionB, String optionC,
			String optionD, String answer, String degree, int csId, String chapter) {
		this.qid = qid;
		this.qtype = qtype;
		this.qtitle = qtitle;
		this.optionA = optionA;
		this.optionB = optionB;
		this.optionC = optionC;
		this.optionD = optionD;
		this.answer = answer;
		this.degree = degree;
		this.csId = csId;
		this.chapter = chapter;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public String getQtype() {
		return this.qtype;
	}

	public void setQtype(String qtype) {
		this.qtype = qtype;
	}

	public String getQtitle() {
		return this.qtitle;
	}

	public void setQtitle(String qtitle) {
		this.qtitle = qtitle;
	}

	public String getOptionA() {
		return this.optionA;
	}

	public void setOptionA(String optionA) {
		this.optionA = optionA;
	}

	public String getOptionB() {
		return this.optionB;
	}

	public void setOptionB(String optionB) {
		this.optionB = optionB;
	}

	public String getOptionC() {
		return this.optionC;
	}

	public void setOptionC(String optionC) {
		this.optionC = optionC;
	}

	public String getOptionD() {
		return this.optionD;
	}

	public void setOptionD(String optionD) {
		this.optionD = optionD;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public int getCsId() {
		return this.csId;
	}

	public void setCsId(int csId) {
		this.csId = csId;
	}

	public String getChapter() {
		return this.chapter;
	}

	public void setChapter(String chapter) {
		this.chapter = chapter;
	}

	public TCourse getCourse() {
		return course;
	}

	public void setCourse(TCourse course) {
		this.course = course;
	}

	@Override
	public String toString() {
		return "TWrittenTest [qid=" + qid + ", qtype=" + qtype + ", qtitle=" + qtitle + ", optionA=" + optionA
				+ ", optionB=" + optionB + ", optionC=" + optionC + ", optionD=" + optionD + ", answer=" + answer
				+ ", degree=" + degree + ", csId=" + csId + ", chapter=" + chapter + "]";
	}

}
