package com.qhit.lh.gr3.cyh.exam.paper.bean;

import com.qhit.lh.gr3.cyh.exam.question.bean.TWrittenTest;

// Generated 2018-1-22 18:38:58 by Hibernate Tools 3.4.0.CR1

/**
 * PaperWrittenTest generated by hbm2java
 */
public class PaperWritten implements java.io.Serializable {

	private int pwid;
	private int pid;
	private int qid;
	
	private TPaper paper;
	private TWrittenTest writtenTest;
	public PaperWritten() {
	}

	public PaperWritten(int pwid, int pid, int qid) {
		this.pwid = pwid;
		this.pid = pid;
		this.qid = qid;
	}

	public int getPwid() {
		return this.pwid;
	}

	public void setPwid(int pwid) {
		this.pwid = pwid;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public TPaper getPaper() {
		return paper;
	}

	public void setPaper(TPaper paper) {
		this.paper = paper;
	}

	public TWrittenTest getWrittenTest() {
		return writtenTest;
	}

	public void setWrittenTest(TWrittenTest writtenTest) {
		this.writtenTest = writtenTest;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PaperWritten [pwid=");
		builder.append(pwid);
		builder.append(", pid=");
		builder.append(pid);
		builder.append(", qid=");
		builder.append(qid);
		builder.append("]");
		return builder.toString();
	}

}
