package com.qhit.lh.gr3.cyh.exam.paper.bean;
// Generated 2018-1-9 17:33:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.qhit.lh.gr3.cyh.exam.classinfo.bean.TClassInfo;

/**
 * PaperClass generated by hbm2java
 */
public class PaperClass implements java.io.Serializable {

	private int pcId;
	private int pid;
	private String ccode;
	private String examDate;
	private String endDate;
	// n-1
	private TPaper pper;
	private TClassInfo classInfo;

	public PaperClass() {
	}

	public PaperClass(int pcId, int pid, String ccode, String examDate, String endDate, TPaper pper,
			TClassInfo classInfo) {
		super();
		this.pcId = pcId;
		this.pid = pid;
		this.ccode = ccode;
		this.examDate = examDate;
		this.endDate = endDate;
		this.pper = pper;
		this.classInfo = classInfo;
	}

	public int getPcId() {
		return this.pcId;
	}

	public void setPcId(int pcId) {
		this.pcId = pcId;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public String getCcode() {
		return this.ccode;
	}

	public void setCcode(String ccode) {
		this.ccode = ccode;
	}

	public String getExamDate() {
		return examDate;
	}

	public void setExamDate(String examDate) {
		this.examDate = examDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public TPaper getPper() {
		return pper;
	}

	public void setPper(TPaper pper) {
		this.pper = pper;
	}

	public TClassInfo getClassInfo() {
		return classInfo;
	}

	public void setClassInfo(TClassInfo classInfo) {
		this.classInfo = classInfo;
	}

	@Override
	public String toString() {
		return "PaperClass [pcId=" + pcId + ", pid=" + pid + ", ccode=" + ccode + ", examDate=" + examDate
				+ ", endDate=" + endDate + "]";
	}

}
