package com.qhit.lh.gr3.cyh.exam.paper.bean;

import java.util.HashSet;
import java.util.Set;

import com.qhit.lh.gr3.cyh.exam.examScores.bean.TUserScores;
import com.qhit.lh.gr3.cyh.exam.question.bean.TCourse;
import com.qhit.lh.gr3.cyh.exam.question.bean.TMachineTest;
import com.qhit.lh.gr3.cyh.exam.question.bean.TWrittenTest;

// Generated 2018-1-9 17:33:24 by Hibernate Tools 3.4.0.CR1

/**
 * TPaper generated by hbm2java
 */
public class TPaper implements java.io.Serializable {

	private int pid;
	private String pname;
	private int ptime;
	private int ptotalScore;
	private int csId;
	private int qtotal;
	private float qscore;
	private String ptype;
	private String pstate;
	//n-1
	private TCourse course;
	//n-n
	private Set<PaperClass> pacls=new HashSet<PaperClass>();
	private Set<TMachineTest> machineTests=new HashSet<TMachineTest>();
	private Set<TWrittenTest> writtenTests=new HashSet<TWrittenTest>();
	//n-1
	private Set<TUserScores> userScores=new HashSet<TUserScores>();
	public TPaper() {
	}

	public TPaper(String pname, int ptime, int ptotalScore, int csId, int qtotal, float qscore, String ptype,
			String pstate, TCourse course, Set<PaperClass> pacls) {
		super();
		this.pname = pname;
		this.ptime = ptime;
		this.ptotalScore = ptotalScore;
		this.csId = csId;
		this.qtotal = qtotal;
		this.qscore = qscore;
		this.ptype = ptype;
		this.pstate = pstate;
		this.course = course;
		this.pacls = pacls;
	}

	public TPaper(int pid, String pname, int ptime, int ptotalScore, int csId, int qtotal, int qscore, String ptype,
			String pstate) {
		this.pid = pid;
		this.pname = pname;
		this.ptime = ptime;
		this.ptotalScore = ptotalScore;
		this.csId = csId;
		this.qtotal = qtotal;
		this.qscore = qscore;
		this.ptype = ptype;
		this.pstate = pstate;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public int getPtime() {
		return this.ptime;
	}

	public void setPtime(int ptime) {
		this.ptime = ptime;
	}

	public int getPtotalScore() {
		return this.ptotalScore;
	}

	public void setPtotalScore(int ptotalScore) {
		this.ptotalScore = ptotalScore;
	}

	public int getCsId() {
		return this.csId;
	}

	public void setCsId(int csId) {
		this.csId = csId;
	}

	public int getQtotal() {
		return this.qtotal;
	}

	public void setQtotal(int qtotal) {
		this.qtotal = qtotal;
	}

	public float getQscore() {
		return qscore;
	}

	public void setQscore(float qscore) {
		this.qscore = qscore;
	}

	public String getPtype() {
		return this.ptype;
	}

	public void setPtype(String ptype) {
		this.ptype = ptype;
	}

	public String getPstate() {
		return this.pstate;
	}

	public void setPstate(String pstate) {
		this.pstate = pstate;
	}

	public TCourse getCourse() {
		return course;
	}

	public void setCourse(TCourse course) {
		this.course = course;
	}

	public Set<PaperClass> getPacls() {
		return pacls;
	}

	public void setPacls(Set<PaperClass> pacls) {
		this.pacls = pacls;
	}

	public Set<TMachineTest> getMachineTests() {
		return machineTests;
	}

	public Set<TWrittenTest> getWrittenTests() {
		return writtenTests;
	}

	public void setMachineTests(Set<TMachineTest> machineTests) {
		this.machineTests = machineTests;
	}

	public void setWrittenTests(Set<TWrittenTest> writtenTests) {
		this.writtenTests = writtenTests;
	}

	public Set<TUserScores> getUserScores() {
		return userScores;
	}

	public void setUserScores(Set<TUserScores> userScores) {
		this.userScores = userScores;
	}

	@Override
	public String toString() {
		return "TPaper [pid=" + pid + ", pname=" + pname + ", ptime=" + ptime + ", ptotalScore=" + ptotalScore
				+ ", csId=" + csId + ", qtotal=" + qtotal + ", qscore=" + qscore + ", ptype=" + ptype + ", pstate="
				+ pstate + "]";
	}

}
